### ISSUE TITLE
problem: mods cannot see users payment details

### ISSUE THREAD

**Issue by gsovereignty** [EmurgoHK/emurgolance#149]
problem: mods cannot see users payment details

**Comment by samuelralak** [comment]
@emurgobot claim

**Comment by samuelralak** [comment]
@emurgobot done

done in #150

**Comment by gsovereignty** [comment]
@AshHimself do you have your bank details in emurgolance?

In production I'm seeing this:

<img width="1447" alt="screen shot 2018-09-21 at 2 20 31 pm" src="https://user-images.githubusercontent.com/8143945/45863654-b050ad00-bda9-11e8-92b3-96716cf99256.png">

Update: I'm seeing this for all users, @samuelralak it could be an issue with your PR for this one.

**Comment by samuelralak** [comment]
Yes @gazhayes , thats definitely. If the payment requests were made before the PR then that should be expected.

**Comment by AshHimself** [comment]
I can't see them, I don't recall. Did you want me to add my new ones? or you still having issues?

**Comment by MadanBhandari** [comment]
@samuelralak  I have one question : How can I make user mod on local [for testing]?

**Comment by samuelralak** [comment]
Hey @MadanBhandari I ran the following directly on my mongo db
```javascript
db.getCollection('users').update({ _id : "CyS2j5Ed5KCaDgfy4" }, { $set : { moderator : true }})
```
where the `_id` is my user's id
